// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  blog_content: dynamic(() => import("./PostBody")),
  hero: dynamic(() => import("./Hero")),
  posts: dynamic(() => import("./Posts")),
};
